/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  static const IconData lock = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData homeActive = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData visibilityOff = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData visibility = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData profile = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData filter = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData add = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData starOutlined = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData star = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData forwardArrow = IconData(0xe815, fontFamily: _kFontFam);

  static const _kFontFam = 'CustomIcons';

  CustomIcons._();
}
