name: docuzer
description: Docuzer project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  app_settings: ^4.1.1
  auto_size_text: ^3.0.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_reorderable_grid_view: ^2.0.2
  flutter_secure_storage: ^5.0.2
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  path_provider: ^2.0.9
  pin_code_fields: ^7.3.0
  photo_view: ^0.13.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/templates/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Black.ttf
          weight: 900
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Thin.ttf
          weight: 200
        - asset: assets/fonts/SFProDisplay/SFProDisplay-Ultralight.ttf
          weight: 100
